name: Crawler

on:
  schedule:
  - cron: '30 2,8 * * *' # 每天上午10点半和下午4点半（UTC时间）执行一次

jobs:
  crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Set up email password
        run: echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      
      - name: Run crawler and send email
        run: python main.py
